// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportTicket.Infrastructure.Persistence;

#nullable disable

namespace SupportTicket.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721070359_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportTicket.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TicketId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Body = "Checking authentication logs for this user account.",
                            CreatedAt = new DateTime(2026, 7, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            TicketId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Body = "Restarted the print spooler service. Monitoring.",
                            CreatedAt = new DateTime(2026, 7, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            TicketId = 2
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Body = "Mail queue was backed up. Cleared and sync is normal now.",
                            CreatedAt = new DateTime(2026, 7, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            TicketId = 3
                        });
                });

            modelBuilder.Entity("SupportTicket.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("Status");

                    b.ToTable("Tickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssigneeId = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User reports 401 error on login page after password reset.",
                            Priority = 2,
                            Status = 0,
                            Title = "Cannot login to portal",
                            UpdatedAt = new DateTime(2026, 7, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AssigneeId = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Office printer on floor 3 is not responding to print jobs.",
                            Priority = 1,
                            Status = 1,
                            Title = "Printer not working",
                            UpdatedAt = new DateTime(2026, 7, 20, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AssigneeId = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 13, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Outlook emails are delayed by 15-20 minutes.",
                            Priority = 0,
                            Status = 2,
                            Title = "Email sync delay",
                            UpdatedAt = new DateTime(2026, 7, 20, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AssigneeId = 3,
                            CreatedAt = new DateTime(2026, 7, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "VPN disconnects every 30 minutes for remote users.",
                            Priority = 2,
                            Status = 3,
                            Title = "VPN connection drops",
                            UpdatedAt = new DateTime(2026, 7, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AssigneeId = 2,
                            CreatedAt = new DateTime(2026, 7, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Employee requested a 27-inch monitor for home office setup.",
                            Priority = 0,
                            Status = 4,
                            Title = "Request new monitor",
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SupportTicket.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@support.com",
                            Name = "Alice Agent"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@support.com",
                            Name = "Bob Agent"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol@support.com",
                            Name = "Carol Manager"
                        });
                });

            modelBuilder.Entity("SupportTicket.Domain.Entities.Comment", b =>
                {
                    b.HasOne("SupportTicket.Domain.Entities.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportTicket.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportTicket.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("SupportTicket.Domain.Entities.User", "Assignee")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("SupportTicket.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SupportTicket.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
